# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='is_d',
        ),
    ]
